# Generated by Django 2.0.5 on 2018-05-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='new email address'),
        ),
    ]
